name: Update LeetCode Stats
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update README
      uses: jwenjian/leetcode-stats-card@main
      with:
        username: YOUR_LEETCODE_USERNAME
        filename: README.md
